name: ci

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install pre-commit
        run: python -m pip install pre-commit
      - name: Configure
        run: ./scripts/configure.sh
      - name: Build
        run: ./scripts/build.sh
      - name: Pre-commit
        run: pre-commit run --all-files
      - name: Test
        run: ./scripts/test.sh
